name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  firebase_core: ^2.32.0
  flutter_local_notifications: ^17.2.1
  go_router: ^13.2.0
  fl_chart: ^0.66.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
